In [62]:
import numpy as np

In [63]:
data = np.loadtxt("wine.txt",delimiter="\t", skiprows=1, usecols=(11,8,2,14))
data_t = data.transpose()

In [64]:
ml = list()
for i in range(len(data_t)):
    m = 0
    for j in range(len(data_t[i])):
        m += data_t[i][j]
    ml.append(m / len(data_t[i]))
# mean_list = [np.mean(data_t[i]) for i in range(len(data_t))]

In [65]:
sdl = list()
for i in range(len(data_t)):
    sd = 0
    for j in range(len(data_t[i])):
        sd += (data_t[i][j] - ml[i]) ** 2
    sdl.append((sd / len(data_t[i])) ** (1/2))
#standard_deviation_list = [np.std(data_t[i]) for i in range(len(data_t))]

In [66]:
dfs = [(data_t[i] - ml[i]) / sdl[i] for i in range(len(data_t))]

In [67]:
cvl = list()
for i in range(len(dfs)):
    cvl_p = list()
    for ip in range(len(dfs)):
        cv = 0
        for j in range(len(dfs[i])):
            cv += dfs[i][j] * dfs[ip][j]
        cvl_p.append(round(cv / len(dfs[i]), 8))
    cvl.append(cvl_p)
#covariance = np.cov(dfs, bias=True)

In [69]:
dfc = np.array(cvl).transpose()

In [73]:
# 固有値と固有ベクトル
eig_val, eig_vec =np.linalg.eig(cvl)

In [74]:
eig_val

array([2.13412213, 1.23808177, 0.33914837, 0.28864774])

In [75]:
eig_vec

array([[-0.40941602,  0.63393186, -0.63654681,  0.15911342],
       [-0.32554699, -0.72535703, -0.56689588, -0.21565111],
       [-0.60560142,  0.16828625,  0.38871533, -0.67366687],
       [-0.59970376, -0.20896726,  0.34976795,  0.68873105]])

In [79]:
# 相関行列の固有ベクトルの第1列を、主成分分析では「第1主成分(PC1)の固有ベクトル」と言います
eig_vec_pc1 = eig_vec[:, 0]
eig_vec_pc1

array([-0.40941602, -0.32554699, -0.60560142, -0.59970376])

In [84]:
# 主成分得点(PC1)
pc1 = np.dot(np.array(dfs).transpose(), eig_vec_pc1)
pc1

array([-1.96711828, -0.84675256, -1.46175988, -3.3874755 , -0.24159879,
       -2.98436965, -2.27094307, -1.99493742, -2.27369861, -1.96136944,
       -2.82416723, -1.9761737 , -1.98989217, -2.68185185, -3.51880515,
       -2.23112285, -2.5554043 , -2.07316301, -3.93797184, -1.00016677,
       -1.33338865, -0.01689935, -1.13612814, -0.3109214 , -0.47834401,
       -0.14656727, -1.39901495, -1.10790099, -1.18003651, -1.34766226,
       -2.08595016, -2.60589258, -0.97273167, -1.79308698, -1.05754468,
       -1.0073638 , -0.594756  , -0.70869744, -0.53256047, -1.27499153,
       -1.11222495, -0.93134552, -1.88881144, -0.12403612, -0.61475952,
       -1.77595886, -1.98422744, -1.75679539, -1.91373859, -2.85680934,
       -1.59162872, -2.01987484, -2.37108792, -2.24366605, -1.57590828,
       -1.58745921, -1.88965548, -1.77474301, -2.41055267,  1.93245298,
        1.25308629,  0.91662625,  0.0234987 ,  0.85377455,  1.83440752,
        0.4815704 , -0.03308605,  1.00068573,  0.31291864,  1.28